# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-24 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
